#!/bin/sh

# Wait for the property system to be up.
while [ ! -e /dev/socket/property_service ]; do sleep 0.1; done

# Enable WIFI
while [ ! -e /dev/wlan ]; do sleep 0.2; done
echo 1 > /dev/ipa && echo ON > /dev/wlan

# fix torch
ERR="flashv2: qpnp_flash_led_brightness_set: Failed to get flash driver data"
echo 0 > /sys/class/leds/flashlight/brightness
if dmesg |  grep -q "$ERR"; then
    mount -o bind /sys/class/leds/led:torch_0/ /sys/class/leds/flashlight
fi
chmod 0666 /sys/class/leds/flashlight/brightness
chmod 0666 /sys/class/leds/led:torch_0/brightness
chmod 0666 /sys/class/leds/led:switch_0/brightness

setprop ubuntu.widi.supported 1

# restart hfd service to enable vibrations
systemctl restart hfd-service.service

